### PR TITLE
Fixes #510: Multiple file uploads via POST now work correctly.

### LINKED ISSUE #510: supporting multiple file upload
### Description

When I define a swagger path like that one:

```
paths:
  /importer:
    post:
      operationId: api.importer.startImport
      description: |
        Start import process.
      consumes:
        - multipart/form-data
      parameters:
        - name: assets
          in: formData
          type: array
          items:
            type: string
            format: binary
```

I am not able to get the "array" of files defined under the name assets. 
Only the first file which is send by the name assets...

`def startImport(xml,importMeta,assets = None) -> object:
    print(assets)`
Result is : `<FileStorage: '25d' ('application/octet-stream')>`

### Expected behaviour

Array of Files should be accessible in the function.

### Actual behaviour

Only one file is send to the function

### Steps to reproduce
Sending 2 File with the key "assets" 

### Additional info:

Output of the commands:

Python 3.6.2
Connexion Version: 1.1.14

### PR DESCRIPTION
**Pull request by simondrabble**
Changes proposed in this pull request:

 Fix issue #510

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks!

**Comment by hjacobs** [comment]
:+1:

**Comment by ddurham2** [comment]
I believe this change breaks the aiohttp api. aiohttp passes a dict and not a wz.datatypes.ImmutableMultiDict as flask does.

**Comment by dtkav** [comment]
Hey @ddurham2 good catch. We have a lot of problems with aiohttp / flask compatibility since the API is not well defined and tests aren't shared between the two frameworks.
#1095 is underway to fix some of the inconsistency in responses, but it's likely we'll have to make some major fixes to ConnexionRequest consistency as well.

**Pull request merged**
