### PR TITLE
Fixes #340 | Convert camelcased parameter names to Python style

### LINKED ISSUE #340: Convert camelcased parameter names to Python style convention
### Description
It's common to define Swagger parameter names in camelcase ("postalCode", "modifiedDate", "statusCode", etc.), but this goes against Python PEP-8 convention.

### Expected behaviour

From Swagger:

    get:
      parameters:
        - name: postalCode
          in: query
          type: string

I would like to be able to write

    def search(postal_code, ...):
        ...

### Actual behaviour

The parameters are not found:

    TypeError: search() missing 1 required positional argument: 'postal_code'

### Additional info:

Output of the commands:

$ python --version
Python 3.5.2
$ pip show connexion | grep "^Version\:"
Version: 1.0.129

Here's a regex for the conversion: http://stackoverflow.com/a/1176023/594211

### PR DESCRIPTION
**Pull request by danballance**
Fixes #340 | Convert camelcased parameter names to Python style

Changes proposed in this pull request:
 - added config variable pythonic_params
 - parameter changes made in parameter_to_arg
 - sanitize_param made a local function within parameter_to_arg so that it can access pythonic_params as a closure and keep the code a little cleaner
- unit tests added with fakeapi and swagger spec

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
@danballance Thank you for the PR! Before I go through the code, could you please check what is causing the tests to fail under the Python interpreter versions >=3.4 ?

Also please fix the ordering of the imports applying this patch:
```patch
--- /home/travis/build/zalando/connexion/connexion/decorators/parameter.py:before	2017-03-09 16:58:03.933834
+++ /home/travis/build/zalando/connexion/connexion/decorators/parameter.py:after	2017-03-09 17:00:57.317468
@@ -3,17 +3,20 @@
 import inspect
 import logging
 import re
+
+import flask
 import inflection
+import six
+import werkzeug.exceptions as exceptions
+
+from ..utils import all_json, boolean, is_null, is_nullable
+
 try:
     import builtins
 except ImportError:
     import __builtin__ as builtins
 
-import flask
-import six
-import werkzeug.exceptions as exceptions
 
-from ..utils import all_json, boolean, is_null, is_nullable
 
 logger = logging.getLogger(__name__)
```

**Comment by danballance** [comment]
@rafaelcaricio certainly, apologies for this, I will look at this today.

**Comment by danballance** [comment]
Blimey, apologies about all of that noise. I _think_ I now have my local development environment set up in such a way that I will catch this stuff locally in future. Do you guys have a doc anywhere with a recommended approach to testing? I had a quick look and couldn't see anything. I'm still not 100% I have things configured optimally.

In terms of the actual PR I guess the main topic to consider is how I am checking the list of built-ins and expecting the called function to have an builtin_ format parameter name for any python built-ins used in the swagger specification. (So  for example path /resource/{id} expects the entry point function to be using id_ for its parameter name.) As I just found out in my unit tests, of course the list of built-ins changes between python versions and would mean that some parameter names would not work. For example reduce is a built-in in Python 2.7 but not in 3.5 so in Python 2.7 we'd require parameter name reduce_ but in Python 3.5 we'd look for the unmodified "reduce".

An alternative approach could be to maintain a common list of variable names such as id and list that we we will handle and not try to handle every built in. Or we could of course drop the automatic handling of built-in shadowed variables.

What do you think is the best way to proceed here? I can make some changes if you think there is a better approach :)

**Comment by rafaelcaricio** [comment]
@danballance Thank you for your PR again and for taking care that all the tests pass.

Your approach looks good to me. I wouldn't worry by the builtins being different between Python versions.

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
