### PR TITLE
Flask Secret Key added

### PR DESCRIPTION
**Pull request by AbhiProjects**
Fixes # .

Changes proposed in this pull request:

 - Adding a secret key will enable the use of Sessions object
 -
 -

### CODE REVIEW

**Comment by hjacobs** [comment]
You can already add the Flask session key via `app.app`. Your PR also contains a lot of unrelated changes (Swagger UI) and no description. Closing. Feel free to open an issue to discuss your problem/solution. Thanks.

**Comment by AbhiProjects** [comment]
Thank you for the flask secret key suggestion via `app.app`

We actually need to restrict the access of /ui and /swagger.json pages to authenticated users.

To restrict access to these web pages, I think we will need to use session mechanisim on console_ui_home method as add_url_rule defined in add_swagger_ui method overrides any routing methods. 

Can you please guide me to a better solution or the above mentioned hack is the only way ?

**Comment by hjacobs** [comment]
@AbhiProjects you can simply add some Flask `before_request` hook to check authentication for `/ui` and `/swagger.json`.

**Comment by AbhiProjects** [comment]
@hjacobs Thank You. `before_request` solved my problem.

**Pull request closed without merging**
