### PR TITLE
Remove old_style_options

### PR DESCRIPTION
**Pull request by dtkav**
Changes proposed in this pull request:
 - retire old_style_options

### CODE REVIEW

**Comment by jmcs** [comment]
Can you adapt the tests and put a note in the readme (make a "Backward Incompatibilities in Connexion 2" section or something similar)?

**Comment by dtkav** [comment]
I can't figure out why code coverage is down. Did I inadvertently disable coroutines somehow?

**Comment by dtkav** [comment]
maybe related to #600 , @dutradda any thoughts?

**Comment by jmcs** [comment]
You removed 42 lines and added 29 (4 of them in the Readme) so there are less covered lines.

**Comment by jmcs** [comment]
👍

**Comment by jmcs** [comment]
Thanks for the PR

**Comment by dtkav** [comment]
What surprised me was a %73 drop in the coverage of `coroutine_wrappers.py`.
Here's the coveralls build link: https://coveralls.io/builds/17946733

**Comment by dutradda** [comment]
@dtkav 

I don't think this is related to #600, because that issue is occurring just with "async def"  functions.

I think that the response decorator only uses the old_style_options on coroutine functions, so when you removed it, the validate_response option is not passed anymore, so the code is never running.

I will take a look on that.

**Pull request merged**
