### PR TITLE
simplify Operation class construction

### PR DESCRIPTION
**Pull request by dtkav**
Follow up to #713 

Changes proposed in this pull request:
 - Introduce make_operation that creates the correct Operation class from a Specification
 - Move Specification classes to separate file (spec.py)

### CODE REVIEW

**Comment by dtkav** [comment]
Hey @cziebuhr , some more refactor - let me know what you think!

**Comment by cziebuhr** [comment]
I would have gone even further, to pass and save the spec object in the operation instead of single parameters in the operation constructor.

**Comment by dtkav** [comment]
I think the current PR is as far as I can go without breaking interfaces or changing tons of tests.

**Comment by dtkav** [comment]
do you want to put up a PR of what you're thinking?

**Comment by cziebuhr** [comment]
> do you want to put up a PR of what you're thinking?

I can do that

**Comment by cziebuhr** [comment]
> do you want to put up a PR of what you're thinking?

I can do that

**Comment by cziebuhr** [comment]
> do you want to put up a PR of what you're thinking?

I can do that

**Comment by jmcs** [comment]
👍

**Pull request merged**
