### PR TITLE
remove test that relies on log output

### PR DESCRIPTION
**Pull request by dtkav**
Changes proposed in this pull request:
 - remove test that relies on log output

### CODE REVIEW

**Comment by dtkav** [comment]
Good morning @jmcs - hope you had a good weekend.
If you have 5 minutes, this PR is tiny - I'm just removing a bad test (no change in coverage).

**Comment by dtkav** [comment]
(or @hjacobs !)

**Comment by jmcs** [comment]
👍

**Comment by dtkav** [comment]
thanks!

**Pull request merged**
