### PR TITLE
Don't let openapi_spec_validator tamper raw spec

### PR DESCRIPTION
**Pull request by cziebuhr**
openapi_spec_validator adds `x-scope` to schemas with `$ref`, which then also get served in `swagger.json`.
```
"$ref" : "#/definitions/Container",
"x-scope" : [
   "",
   "#/definitions/InstanceStats"
]
```
In my case, bravado (which internally uses swagger_spec_validator) fails using the spec:
```
jsonschema.exceptions.RefResolutionError: unknown url type: ''
```

### CODE REVIEW

**Comment by dtkav** [comment]
What about using the spec that's passed in, and moving validation before resolving refs?
That would avoid another deepcopy.
```
     def __init__(self, raw_spec):
         self._raw_spec = copy.deepcopy(raw_spec)
         self._set_defaults()
         self._validate_spec(raw_spec)  # change to a staticmethod
         self._spec = resolve_refs(raw_spec)
```

**Comment by cziebuhr** [comment]
That's also possible, if it's ok that the passed dict will get changed.

**Comment by dtkav** [comment]
it is already changed by the ref resolver, so I think the only risk is that
the validator and ref resolver have some interaction.

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
