### PR TITLE
Reorganize imports

### PR DESCRIPTION
**Pull request by rafaelcaricio**
We had many different ways to organize our imports until now. I think it is nice to adopt a common way to write our imports and even better have it automatically fixed.

Changes proposed in this pull request:

 - Ran the `isort` development tool to reorganise our imports automatically
 - Added the isort check step into the `tox` tests pipeline (`$ tox -e isort-check`)
 - Use `tox` tool in travis testing pipeline
 - Set 100% test coverage

### CODE REVIEW

**Comment by jmcs** [comment]
Please fix the conflicts.

**Comment by rafaelcaricio** [comment]
@jmcs Fixed.

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
@hjacobs Could you please take a look on this PR? Do you think anything is missing here?

**Comment by hjacobs** [comment]
LGTM

**Pull request merged**
