### PR TITLE
Downgrade log message severity when there are multiple security definitions

### PR DESCRIPTION
**Pull request by jakul**
My Swagger spec has multiple security definitions (for Basic auth and JWT/Bearer auth), and whenever I start my server I see lots of output telling me that Connexion isn't going to verify the passed credentials.

This PR downgrades the message severity. There is a similar message at debug level for when the API has Basic auth, as Connexion doesn't validate that either.

```
py27-dredd runtests: commands[1] | ./test_api.sh
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
info: Configuration './dredd.yml' found, ignoring other arguments.
info: Starting backend server process with command: python ./run.py
info: Waiting 3 seconds for backend server process to start.
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:20] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
```

Changes proposed in this pull request:

 - Downgrade message severity

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
It makes sense to me.

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
I'm not entirely sure --- while I clearly see that there is a lot of log spamming, it's quite a dangerous (and unexpected) behavior of Connexion just ignoring multiple security definitions without any warning or informational output. I generally expect software to "work as expected" and tell me if it cannot do so (ignoring multiple security defs is certainly "not working as expected" from the user POV).

**Comment by jakul** [comment]
I can understand your point. The counterpoint I can give is that Connexion
already ignores security definitions for APIs which only have basic auth
without warnings or output (other than than at debug level). I also think
that it'll never be possibly for Connexion to verify every arbitrary
security method that could be implemented in an API, so making so much log
output in those cases is not helpful.

Another solution I could propose would be to log that particular message to
a sub logger, which would let me disable that logger in my application
without changing the semantics for anyone else.

Em ter, 9 de mai de 2017 21:35, Henning Jacobs <notifications@github.com>
escreveu:

**Comment by hjacobs** [comment]
@jakul you convinced me with the example of Connexion silently ignoring basic auth if there is only one security def! :smile:

**Comment by hjacobs** [comment]
:+1:

**Comment by jakul** [comment]
Yaaaaay 🎉

Thanks for the good work on this library guys. It's helped me to enforce
"documentation first" APIs at work, instead of the "what's documentation?"
APIs we had before 😀

Em ter, 9 de mai de 2017 22:30, Henning Jacobs <notifications@github.com>
escreveu:

**Comment by hjacobs** [comment]
@jakul thanks for the nice words and yes, I also struggle with people seeing Swagger/OpenAPI primarily as "documentation" (i.e. they regard it as an afterthought).

**Pull request merged**
