### PR TITLE
update swagger UI to v3.x.x

### PR DESCRIPTION
**Pull request by erinaceous**
Changes proposed in this pull request:

 - Updated swagger UI to v3.x.x: This removes backwards compatibility with swagger specifications older than version 2 specs, but it fixes some issues I've been having with my existing v2 spec.

Could you keep this as another branch on the project?

Although I see that the swagger UI may be removed from connexion in future according to issue #406 ...

### CODE REVIEW

**Comment by xylix** [comment]
I'm also having some problems with connexion's current swagger-UI version.

**Comment by rafaelcaricio** [comment]
@xylix You don't need to use Connexion's Swagger UI version. Please check out the https://github.com/zalando/connexion/blob/master/connexion/cli.py#L65-L66 option, the `swagger_path` parameter in the [App](https://github.com/zalando/connexion/blob/master/connexion/cli.py#L134) to use your own updated version of the Swagger UI.

**Comment by xylix** [comment]
@rafaelcaricio Oh allright thanks a lot.

**Comment by rafaelcaricio** [comment]
Just to make it clear why I close this here. I closed this because it is not safe to allow anyone besides the maintainers team to update the Swagger UI code. Some "funny code" can be added since the PR is impossible to review properly.

**Comment by NightBlues** [comment]
>  I closed this because it is not safe to allow anyone besides the maintainers team to update the Swagger UI code.
Good thought. Could you please update swagger_ui by yourself, or there are other reasons for staying with version 1 year old?

**Comment by rafaelcaricio** [comment]
@hjacobs was updating this part of the project. Could you please update @hjacobs?

@NightBlues Please check out the https://github.com/zalando/connexion/blob/master/connexion/cli.py#L65-L66 option as well.

**Pull request closed without merging**
