### PR TITLE
Drop Python 2.7 support

### PR DESCRIPTION
**Pull request by kornicameister**
Partially #998 

Changes proposed in this pull request:
 - removed 2.7 from classifiers
 - removed all references to 2.7
 - code cleanup

### CODE REVIEW

**Comment by hjacobs** [comment]
Tests are failing.

**Comment by kornicameister** [comment]
@hjacobs I know that. That's why that's a draft :)

**Comment by badcure** [comment]
While Python 2.7 is officially ending on January, Redhat will continue to support it to some degree: https://access.redhat.com/solutions/4455511

This decision either way won't affect me, but just something I believe to be considered. Essentially an immediate drop in support vs dropping support in the next major release(i.e. deprecating for now).

**Comment by kornicameister** [comment]
@badcure the decision like that ain't my call. I have few minutes to try and deal with moving this PR further and that's exactly what I am going to do.

**Comment by kornicameister** [comment]
Tests are flowing right not at my laptop. There's nothing much to do apart from to decide what to do with `2.7` occurrences in following files:

```
tests/test_validation.py
tests/test_utils.py
tests/decorators/test_parameter.py
connexion/decorators/coroutine_wrappers.py
connexion/decorators/response.py
```

as well as clearing up this situation:
```
# we are using "mock" module here for Py 2.7 support
from mock import MagicMock
```

which, I am not mistaken can be resolved via:
```
[pytest]
mock_use_standalone_module = true
```
and `pytest-mock`.

**Comment by hjacobs** [comment]
@kornicameister thanks! We can further clean up Python 2.7 references in a new PR.

**Comment by hjacobs** [comment]
:+1:

**Comment by kornicameister** [comment]
@hjacobs yes we can. The point is that I or someone else need to know how to do that. What's your expectation here. I am sorry to say, but I had first day (today) since a week, where I had time and strength to sit in the evening and to code something up. Even though there is something inside of me to push this one I am afraid I won't find it in me to do that. It's a bit of a rough time for me now and I am simply exhausted.

It's just something for you to consider, I don't want it to sound as if I am telling you how to drive the project.

**Comment by hjacobs** [comment]
@kornicameister I think it's not urgent and I created an issue to not forget the follow-up: https://github.com/zalando/connexion/issues/1065

**Pull request merged**
