### PR TITLE
Adding custom validators

### PR DESCRIPTION
**Pull request by menudoproblema**
Changes proposed in this pull request:

 - Support for custom validators

This example returns the complete list of validation errors instead of returning a single error:

    from connexion.decorators.validation import RequestBodyValidator
    from connexion.problem import problem
    from connexion.utils import is_null
    from jsonschema.validators import validator_for

    class CustomRequestBodyValidator(RequestBodyValidator):
        def validate_schema(self, data):
            if self.is_null_value_valid and is_null(data):
                return None

            cls = validator_for(self.schema)
            cls.check_schema(self.schema)
            errors = tuple(cls(self.schema).iter_errors(data))

            if errors:
                error_list = [ e.message for e in errors ]
                return problem(400, 'Bad Request', {'errors': error_list}, type='validation')

            return None

    if __name__ == '__main__':
        validator_map = {
            'body': CustomRequestBodyValidator,
        }
        app = connexion.App(__name__, ..., validator_map=validator_map)

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
Thank you for the PR and it looks interesting. Before we check it deeper, could you please fix the tests?

**Comment by menudoproblema** [comment]
Sure! :)

**Comment by menudoproblema** [comment]
I'm not sure what's wrong with isort. That's my local output:

$ python --version
Python 3.5.0
$ isort -ns __init__.py -rc -c connexion --verbose

/#######################################################################\

     `sMMy`
     .yyyy-                                                      `
    ##soos##                                                    ./o.
          `     ``..-..`         ``...`.``         `   ```` ``-ssso```
     .s:-y-   .+osssssso/.     ./ossss+:so+:`    :+o-`/osso:+sssssssso/
     .s::y-   osss+.``.``     -ssss+-.`-ossso`   ssssso/::..::+ssss:::.
     .s::y-   /ssss+//:-.`   `ssss+     `ssss+   sssso`       :ssss`
     .s::y-   `-/+oossssso/  `ssss/      sssso   ssss/        :ssss`
     .y-/y-       ````:ssss`  ossso.    :ssss:   ssss/        :ssss.
     `/so:`    `-//::/osss+   `+ssss+-/ossso:    /sso-        `osssso/.
       \/      `-/oooo++/-      .:/++:/++/-`      ..           `://++/.


         isort your Python imports for you so you don't have to

                            VERSION 4.2.5

\########################################################################/

SUCCESS: /Users/uve/connexion/connexion/api.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/app.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/exceptions.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/handlers.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/operation.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/problem.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/resolver.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/utils.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/decorator.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/metrics.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/parameter.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/produces.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/response.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/security.py Everything Looks Good!
SUCCESS: /Users/uve/connexion/connexion/decorators/validation.py Everything Looks Good!
WARNING: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
WARNING: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
Skipped 2 files

**Comment by rafaelcaricio** [comment]
Could you please try locally:
```
$ tox -r -e isort-check
```
And see the output?

**Comment by rafaelcaricio** [comment]
Could you please also write some tests so we guarantee it will keep working as expected moving forward?

**Comment by rafaelcaricio** [comment]
@menudoproblema Hi, I've sent a PR to your branch to fix those issues with Flake8. Could you please take a look? If you do not have time to work on this issue, please let me know and I will try to move this forward myself.

**Comment by rafaelcaricio** [comment]
Replaced by #281

**Pull request closed without merging**
