### PR TITLE
Falcon web framework

### PR DESCRIPTION
**Pull request by hjacobs**
** WORK IN PROGRESS **

Add support for the Falcon web framework as an alternative to Flask.

[Falcon](https://falconframework.org/) is a very fast, very minimal Python web framework.

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
Just wondering if this should be in the main repo.

**Comment by p1c2u** [comment]
Is it still alive?

**Comment by webwurst** [comment]
I don't want to distract, but came across another promising framework that is "Flask-like" on the API level and also claims to be really fast: https://github.com/channelcat/sanic

> On top of being Flask-like, Sanic supports async request handlers. This means you can use the new shiny async/await syntax from Python 3.5, making your code non-blocking and speedy.

**Comment by thatrevguy** [comment]
Is this branch still active?

**Comment by hjacobs** [comment]
@thatrevguy no, honestly I won't get around working on this. It probably makes sense to close the PR.

**Comment by SamPenrose** [comment]
Would you accept a PR for this functionality, based on your existing work? If so, can you estimate how long it would take *you* to do it? (I will then multiply that by 2-5 to estimate how long it will take me :-).)

**Comment by hjacobs** [comment]
@SamPenrose I honestly don't know, I did not touch the code for a long time and would have to get up to speed first. From my current perspective I also doubt the value of integrating the Falcon framework (it's potentially more lightweight, but it adds code to be maintained).

**Comment by SamPenrose** [comment]
@hjacobs Thanks for update. Regarding value, it would add value to those of us who have to use falcon for other reasons and would love to try Connexion :-). I really like the design you chose. I will work on my project and maybe get back to you if I think a port is worth considering.

**Comment by hjacobs** [comment]
@SamPenrose sounds good, thanks!

**Comment by hjacobs** [comment]
Not working on this anymore.

**Pull request closed without merging**
