### PR TITLE
Copy spec before validation occurs

### LINKED ISSUE #214: swagger_spec_validator adds in x-scope property to definitions
When validating the swagger document the dictionary that is passed to `swagger_spec_validator.validator20` is modified. It is possible for that library to add in any properties it wants to the spec.

Expected behavior, validation doesn't add in extra properties like `x-scope` to references.

Actual behavior, validation adds in extra properties like `x-scope` to references which can cause issues when using swagger clients that rely on the swagger_spec validator (like bravado). If the validator sets `x-scope` to the empty string then the bravado client can't properly understand where those references point to.

This was in a new connexion project, the swagger document had parameters defined as references.  

### Additional info:

Output of the commands:

- `python --version`
`Python 3.5.1`
- `pip show connexion | grep "^Version\:"`
`Version: 1.0.89`

This is related to this issue though allowing only a copy of the spec to be passed into the validator is a good idea on this side as well. https://github.com/Yelp/swagger_spec_validator/pull/48

### PR DESCRIPTION
**Pull request by wasbazi**
Fixes #214 

Changes proposed in this pull request:
 - Copies the spec and passes the copy to validator instead of passing the original spec used later in the code

### CODE REVIEW

**Comment by jmcs** [comment]
Thanks for the pull request.

Do you have any bug caused by not deep copying the specification?

Please note that we can only merge your pull request after the failing unit test is fixed.

**Comment by rafaelcaricio** [comment]
@wasbazi  Why would you like to change that? Could you please elaborate in the problem you are having?

**Comment by rafaelcaricio** [comment]
@wasbazi Sounds good, but you have to do:

```python
self.specification = compatibility_layer(spec)
```

Because Connexion expects that the status codes to be integer value, probably that is why the tests are failing now.

**Comment by wasbazi** [comment]
Thanks for pointing that out, just noticed the failing build and will fix that!

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
