### PR TITLE
Python 3.8: replace @asyncio.coroutine/yield from with async/await #1182

### LINKED ISSUE #1182: Python 3.8 asyncio.coroutine deprecated
### Description

In Python 3.8 `@asyncio.coroutine` was deprecated. It's gonna be removed in Python 3.10. I saw other PRs that stop using `loop` parameter, but still `@asyncio.coroutine` is used in multiple places.

### Expected behaviour

No warnings should be displayed when using connexion.

### Actual behaviour

```
/builds/[redacted]/.tox/py38/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py:48
  /builds/[redacted]/.tox/py38/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py:48: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def problems_middleware(request, handler):
```

### Steps to reproduce

Run any tests on Python 3.8 (requirements we use: `connexion[aiohttp, swagger-ui]==2.6.0`

### Additional info:

Output of the commands:

- `python --version`: `Python 3.8.2`
- `pip show connexion | grep "^Version\:"`: `Version: 2.6.0`

### PR DESCRIPTION
**Pull request by szborows**
Fixes #1182 .

Changes proposed in this pull request:

 - replaced `@asyncio.coroutine` and `yield from` with `async` and `await` respectively

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by szborows** [comment]
@hjacobs I think you need to use `await` instead of `yield from`

**Comment by szborows** [comment]
@hjacobs it's green except coverage. Please advise: what to do with this -0.005%?

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
