### PR TITLE
Feature/option to disable swagger json

### PR DESCRIPTION
**Pull request by dfeinzeig**
Adds an option to disable the swagger.json route when creating an app or adding an api.  You may not want this exposed, particularly if you've added security to your other routes.

Changes proposed in this pull request:
- adds swagger_json boolean to app and api with proper glue bits
- adds tests
- updates docs

### CODE REVIEW

**Comment by jmcs** [comment]
Thanks for the Pull Request, and a special thanks for updating the test and the documentation.

**Comment by dfeinzeig** [comment]
No problem.  Is it possible to do a new release to pypi?  Looks like it has been a few weeks.

**Comment by hjacobs** [comment]
@dfeinzeig done: https://github.com/zalando/connexion/releases/tag/1.0.81

**Comment by dfeinzeig** [comment]
thank you @hjacobs !

**Pull request merged**
