### PR TITLE
Flask request user support

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Follow up on #428. For backward compatibility adds values assigned to `ConnexionRequest.context` to current `flask.request`.

### CODE REVIEW

**Comment by danballance** [comment]
Hi guys, what's the best way for me to adapt my code here? Lots of stuff has broken for me with 1.1.7. I was perhaps naively relying on the uid being set in flask.request.user in my application. What's the recommended way to refactor here?

**Comment by rafaelcaricio** [comment]
@danballance After this PR gets merged it should probably just work again for you.

**Comment by rafaelcaricio** [comment]
@danballance My apps also rely on `flask.request.user`... 😝

**Comment by rafaelcaricio** [comment]
@hjacobs could you please review? I will release a new version of Connexion after this PR gets merged.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@rafaelcaricio please release :smile:

**Pull request merged**
