### PR TITLE
Replacing deprecated flask json calls + Content-Type validation

### PR DESCRIPTION
**Pull request by jeff-99**
Hi, 

While debugging a vague error message ("None type is not of type object"). I came across some deprecated Flask code, so I changed it.

The reason i got the error message was because I had forgotten to set a content-type header to "application/json" in Postman. I thought it would be useful to improve the error message when this happens. 

Let met know what you think!

Changes proposed in this pull request:

 - refactoring flask.request.json calls to flask.request.get_json()
 - Improving error messages when an http request does contain data but lacks a proper content-type

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR! :smile:

**Comment by hjacobs** [comment]
There are some unit test failures on Travis CI..

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
@rafaelcaricio why do we ignore the failing Travis CI tests?

**Comment by rafaelcaricio** [comment]
@hjacobs I am not ignoring, that's why it is not merged yet. I am trying to figure out what is causing it.

**Comment by rafaelcaricio** [comment]
@hjacobs Found the issue, fixed in https://github.com/zalando/connexion/pull/398. After #398 gets merged I would like to ask @jeff-99 to rebase this PR so we can merge it as well.

**Comment by hjacobs** [comment]
@jeff-99 #398 was merged, can you rebase this PR please?

**Comment by hjacobs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
