### PR TITLE
Hoist Operation from closure to class variable

### PR DESCRIPTION
**Pull request by kislyuk**
This makes connexion.Api more extensible by inheritance.

### CODE REVIEW

**Comment by hjacobs** [comment]
@kislyuk if this should become part of the Connexion API (and people rely on it), could you add a test for this (i.e. overwriting `operation_cls`)? Thanks!

**Comment by jmcs** [comment]
@kislyuk are you still interested in getting this PR merged?

**Comment by kislyuk** [comment]
Yes, but I have no bandwidth to add the tests.

**Comment by RobbeSneyders** [comment]
Closing since this has been refactored and exposed in #726.

**Pull request closed without merging**
