### PR TITLE
Add sanitized_params option to allow disabling sanitization

### LINKED ISSUE #835: Sanitization removes sensible characters in API definition and json request body input
### Description

I am using Connexion v2.2.0 to build an API that handles json schemata.

Request bodies containing schemata with a field name containing characters other than [0-9a-zA-Z_] are removed while parsing the request and passed to the handlers sanitized. 
This leads to unexpected behavior. 

The sanitization done in method `parameter_to_arg` (in file `connexion/decorators/parameter.py`) removes sensible characters such as `$` that are used in both API definition and json body input such as in fields "$id" and "$schema". Those field names are common in json schematas following version 06, for example.

### Expected behaviour

For example, a valid json {"$id": "...", ...} is used in the call and it should be passed to the handlers as is.

### Actual behaviour

Following the above example, a valid json {"$id": "...", ...} used in the call is passed to the handlers as {"id": "...", ...}.

### Steps to reproduce

Assume the following API definition (`api.yaml`):
```yaml
openapi: "3.0.0"
info:
  title: "Some API"
  version: "0.0.1"
servers:
- url: /
paths:
  /test:
    post:
      operationId: app.test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              x-body-name: body
              type: object
              properties:
                "$id":
                  type: string
      responses:
        200:
          description: Response.
```
that uses `test(body)`, in `app.py`, as its handler, which is defined as
```python
import connexion

def test(body):
    import json
    print(json.dumps(body, indent=2))
    return json.dumps(body, indent=2), 200

app = connexion.FlaskApp(
    __name__,
    specification_dir="./")
app.add_api("api.yaml", validate_responses=True)
app.run(port=8080)
```

Calling the above endpoint with `curl -X POST -H "Content-Type: application/json" localhost:5001/test -d '{"$id": "myid"}'`, the output of the handler `test` is 
```json
{
  "id": "myid"
}
```
instead of the expected 
```json
{
  "$id": "myid"
}
```

### Additional info:

- `python --version`:  
  Python 3.6.7 :: Anaconda, Inc.

- `pip show connexion | grep "^Version\:"`:  
  Version: 2.2.0

### PR DESCRIPTION
**Pull request by ptamilarasan**
Fixes #835 .

Changes proposed in this pull request:

 - Ability to disable sanitization

This is useful when the keys in a JSON post body contains characters like `-` or `$`

### CODE REVIEW

**Comment by dtkav** [comment]
I'd suggest we start with #1008 , and then see if it's still a problem for folks still using openapi2.
Let me know what you think!

**Comment by ptamilarasan** [comment]
I'm fine with #1008 instead, as its probably the more correct way to handle this.  When I get a chance I'll test the other PR and see if it addresses our issue.  You mentioned openapi2 but we were affected by this in openapi 3.

**Comment by hjacobs** [comment]
Is this still needed after merging #1008?

**Comment by dtkav** [comment]
I'm pretty sure #1008 resolves this, so I'll close it for now.
Please re-open if I missed something!

**Pull request closed without merging**
