### PR TITLE
remove type hint for options in App.run(...)

### LINKED ISSUE #645: Type warning when giving Werkzeug-specific options arguments to App.run() in development mode
### Description
When one will give a Werkzeug-specific argument to `App.run()` which will be passed by the connexion app to the underlying Werkzeug server in development mode, IDEs like PyCharm will warn, that the type of the given argument does not match the expected type, which is stated in the function's docstring to be `dict`. No matter the warning everything seems to work as expected.

### Expected behaviour
No warning

### Actual behaviour
Warning

### Steps to reproduce
Insert this code in PyCharm:
```
import connexion
from connexion import RestyResolver
import pathlib

app = connexion.App(__name__, specification_dir='./')
app.add_api(pathlib.Path('swagger.yml'), resolver=RestyResolver(default_module_name='backend.api'), strict_validation=True)


if __name__ == '__main__':
    app.run(threaded=False)
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.5.2
- `pip show connexion | grep "^Version\:"`
Version: 1.5.2
- `pip show flask | grep "^Version\:"`
Version: 1.0.2

### PR DESCRIPTION
**Pull request by dtkav**
Fixes #645 

@paulkernstock can you verify that this fixes your problem?

### CODE REVIEW

**Comment by paulkernstock** [comment]
> Fixes #645
> 
> @paulkernstock can you verify that this fixes your problem?

@dtkav Unfortunately not. There's another type hint at `apps.flask_app.FlaskApp.run()` that overrides the hint you changed in the abstract module.

**Comment by dtkav** [comment]
@paulkernstock can you have another look? FYI I rebased onto dev-2.0 instead of master, as the release is imminent!

**Comment by paulkernstock** [comment]
Fixed. Thanks!

**Comment by jmcs** [comment]
@dtkav I merged this in dev-2.0 can you rebase your branch in master and resubmit the PR? Thanks

**Comment by dtkav** [comment]
yeah - sure thing

**Comment by dtkav** [comment]
#766

**Pull request merged**
