### PR TITLE
Allow users to enable debug mode via environment variables

### LINKED ISSUE #1083: Can't use environment variables to enable flask debug mode
### Description

With Flask we can enable debug mode by using flask environment variables like explained here : https://flask.palletsprojects.com/en/1.1.x/config/#environment-and-debug-features

It seems that `AbstractApp` enforces `debug=False` (in its constructor params) so if we call `app.run()` without the `debug` param, `FlaskApp` is calling app.run with `debug=False`)

A simple way to fix this would be to use `debug=None` instead of `debug=False` but I don't know what is the impact for other app types.

### Expected behaviour

Using `FLASK_ENV=development` or `FLASK_DEBUG=True` should enable debug mode on Flask applications

### Actual behaviour

Using `FLASK_ENV=development`runs flask in development environment bug debug mode is off :

```
 * Serving Flask app "myapp" (lazy loading)
 * Environment: development
 * Debug mode: off
```

### Steps to reproduce

Don't use the `debug` parameter in `app.run()` call and set `FLASK_ENV` variable to `development`.

### Additional info:

Python's version: 3.7.1
Connexion's version: 2.4.0

### PR DESCRIPTION
**Pull request by cedricmessiant**
Fixes #1083 

Changes proposed in this pull request:

 - use `None` as default value for `debug` parameter in `AbstractApp` to allow users to use flask environment variables to activate debug mode

### CODE REVIEW

**Comment by dtkav** [comment]
Does this change the default behavior?
When you pass `None` does flask default to `True` or `False`?

**Comment by cedricmessiant** [comment]
Do you mean connexion's default behavior or flask's?
By default in flask, debug is set to `None` in `flask/app.py`. Then, it uses the configuration variables (`FLASK_ENV`  or `FLASK_DEBUG`) or the parameter that `run()` method takes (it defaults to `None` also)

**Comment by hjacobs** [comment]
I think this change should have some comment as it's easy to forget why it is now `None` and not `False` --- also a unit test would be nice.

**Comment by dtkav** [comment]
yeah @cedricmessiant , does it change the default connexion behavior? We don't want to accidentally cause everyone to run in debugg mode when they upgrade.

**Comment by cedricmessiant** [comment]
@dtkav yeah, no problem when I run the `helloworld` example (no option passed to `run()`, it runs with debug mode off). 

@hjacobs I added a test (and put a comment about debug in the test, maybe we could add a link to this MR/issue but I don't think it's necessary)

**Comment by hjacobs** [comment]
:+1:

**Comment by cedricmessiant** [comment]
Thanks a lot !

**Pull request merged**
