### PR TITLE
Use Authorization headers for verifying token info

### LINKED ISSUE #541: verify_oauth uses url params instead of Authorization headers for token info
### Description

``verify_oauth`` uses url params instead of Authorization headers for token info.
Using Authorization header is the recommended way for verifying tokens.

Using url params could lead to leaking access tokens to external services. We faced this issue during testing OpenTracing. Authorization headers provides a more structured way in preventing leaking access tokens (e.g. in opentracing tags).

### Expected behaviour

Using Authorization headers for verifying tokens.

### Actual behaviour

Using URL params for verifying tokens.

### Additional info:

Output of the commands:

- `python --version`
Python 3.5.2
- `pip show connexion | grep "^Version\:"`

### PR DESCRIPTION
**Pull request by mohabusama**
Fixes #541 

Changes proposed in this pull request:

 - Change token info verification to use Authorization headers rather than url params.

Note: Not sure if url params is a requirement, left it in the test case fixture, but could be removed if Authorization headers would suffice.

### CODE REVIEW

**Comment by hjacobs** [comment]
@mohabusama please also update the oauth2 example in the `examples` folder: https://github.com/zalando/connexion/tree/master/examples/oauth2

**Comment by mohabusama** [comment]
@hjacobs Done.

**Comment by hjacobs** [comment]
:+1:

**Comment by kislyuk** [comment]
This breaks compatibility with the Google tokeninfo API. It would be nice if this could be reverted, released on a hotfix basis, and then made configurable and re-committed.

**Comment by hjacobs** [comment]
@kislyuk do you have some doc regarding Google tokeninfo? It's definitely wrong if they propose passing the token as a query parameter. See also https://tools.ietf.org/html/rfc7662:

```
To prevent the values of access tokens from leaking into server-side
logs via query parameters, an authorization server offering token
introspection MAY disallow the use of HTTP GET on the introspection
endpoint and instead require the HTTP POST method to be used at the
introspection endpoint.
```
(token introspection is the effort to standardize the tokeninfo idea)

**Comment by komasoftware** [comment]
While Google token info maybe wrong in passing the token only as a query parameter, it is one of the most used authentication methods. Killing it off makes this library unusable for a lot of use cases.

**Comment by mohabusama** [comment]
@kislyuk @komasoftware I have created this issue to enable verification using url params as a configuration.

I have checked [Google token info docs](https://developers.google.com/identity/sign-in/web/backend-auth) and it seems to me that it accepts ``id_token`` as param and not ``access_token`` as implemented in Connexion. Was wondering if this actually worked before out-of-the-box?

**Comment by kislyuk** [comment]
It did work before. I don't recall the details. I had to lock my requirements to a version of connexion before this change was made.

**Comment by kislyuk** [comment]
OK, I recall now. We used connexion just for the auth middleware, not for the oauth roundtrip. The token was obtained independently of connexion. However, the update broke the auth middleware, since it became unable to successfully call the tokeninfo route to verify the token. You can see the Swagger YAML for the app in question here: https://github.com/HumanCellAtlas/data-store/blob/master/dss-api.yml

**Comment by komasoftware** [comment]
Rolling back to version connexion==1.1.15
This config works :
  googAuth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
    x-tokenInfoUrl: https://www.googleapis.com/oauth2/v3/tokeninfo
    scopes:
      https://www.googleapis.com/auth/userinfo.email: read user email
But not with the latest release

**Pull request merged**
