### PR TITLE
update Swagger UI from upstream (using ./update.sh 2.2.5)

### PR DESCRIPTION
**Pull request by hjacobs**
Update Swagger UI to latest upstream release (2.2.5).

* add `update.sh` to have a reproducible process (this PR is the result of `./update.sh 2.2.5`)
* add `index.html.patch` to fix URL and disable online validator

This PR is addressing the issues we had with #303.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
Why do we need to have the whole code of swagger ui in this repo?

**Comment by rafaelcaricio** [comment]
Can't we just check it out during the process of building a new version in the CI?

**Comment by hjacobs** [comment]
@rafaelcaricio let's discuss the general approach of how to include Swagger UI later on (maybe package for PyPI?).

**Pull request merged**
