### PR TITLE
Preserving the multiplicity of array type query parameters

### PR DESCRIPTION
**Pull request by lhannest**
Fixes issue #323

This is a better implementation of what I was doing in the #499 pull request.

Changes proposed in this pull request:

 - On line 146 of parameter.py: updating the request query parameters being added to `query_arguments` so as to preserve lists that are encoded by having multiple values to a single key.

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR! Could you check the failing test (see https://travis-ci.org/zalando/connexion/jobs/260404325) and add a test for the array parameter?

**Comment by lhannest** [comment]
This PR isn't really a fix for #323. It's really just a partial solution that will allow users to get the functionality of multi formatted arrays. But I have not done anything to support a multi collection format in the swagger.yaml specification file.

Before, only the first of multiple keys would be accepted. Now they will all be accepted. So doing `/api?items=A,B,C&items=D` will be the same as doing `items=A,B,C,D` as long as the collection format is csv. On the other hand, if the collection format is pipes, then `/api?items=A,B,C&items=D` will be the same as doing `/api?items=A,B,C|D`.

**Comment by lhannest** [comment]
@hjacobs do you have any other thoughts?

**Comment by lhannest** [comment]
It's been two weeks, can the "waiting for contributor feedback" label be removed at least so someone eventually gets around to looking at this PR?

**Comment by hjacobs** [comment]
@lhannest sorry for the the slow response, @jmcs can you take a look?

**Comment by lhannest** [comment]
@mvalkon Thank you for the review, and sorry for taking a while to respond. I pushed the changes you suggested.

**Comment by mvalkon** [comment]
@lhannest lgtm, thanks for the contribution!

**Comment by mvalkon** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
