### PR TITLE
Attempt to better log the validation error responses receive in

### PR DESCRIPTION
**Pull request by danballance**
So this is my proposal for enhancement  #153 

So the main difficulty is that RequestBodyValidator.validate_schema() returns a problem like so:

problem(400, 'Bad Request', str(exception))

So the exception is basically cast to a string - even though this is quite a complex python data structure in the case of these validation errors.

So my small tweak is to use the ast module to safely convert this string back to a python data structure. I then attempt a couple of sanity checks - it's a list with at least one item - and then pull the error dictionary out. Once I have this object I'm able to log the error in a way that is easier to read (for me at least!) than just logging the returned string representation of the error.

Do you think this is worth doing? Is it safe? I'm not too sure about what RequestBodyValidator is doing - handling the error from json-schema I assume?

I've also not been able to test this properly under Python 3. It seems to work fine with 2.7 in my tests so far. Feedback welcomed :)

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
Hi @danballance , first of all -- thank you very much for working in that issue.

Before I start digging into your PR. Please update your master branch (your fork) and then create a new branch and cherry-pick the most important commit https://github.com/danballance/connexion/commit/ceda46f3ecfa011c31afdcec40f929f142942311 and send a new PR with that new branch. The thing is that I rather not merge this commit https://github.com/danballance/connexion/commit/d6b88c3ba5cc9d88fd6ccb3910b95730fc843987 which is useless.

**Comment by rafaelcaricio** [comment]
TL;TR:
Please do it:
```bash
git checkout master
git remote add original git@github.com:zalando/connexion.git
git pull original master
git checkout -b new-pr
git cherry-pick ceda46f
```
And send a new Pull Request from your new branch `new-pr`.
 :)

**Comment by danballance** [comment]
Apologies for the delay here - I missed the Github email notification. I have created a new pull request #175 that is hopefully a cleaner commit and what you are looking or :)

**Comment by rafaelcaricio** [comment]
replaced by #175.

**Pull request closed without merging**
