### PR TITLE
Pin test versions

### PR DESCRIPTION
**Pull request by RobbeSneyders**
This PR adds upper limits to the versions of packages used in our CICD pipeline as proposed by @rafaelcaricio in #1367.

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
No idea why Coveralls is failing since coverage stayed exactly the same. We might want to increase the failure threshold on [coveralls.io](coveralls.io), but I don't have access and it's not clear who the owner is. While we're at it, we should also update the default branch to `main` there.

**Review by rafaelcaricio — APPROVED** [review]

**Comment by jmcs** [comment]
I changed the coveralls decrease threshold to 0.5%.

**Review by hjacobs — APPROVED** [review]

**Comment by miguelgf** [comment]
Hello @RobbeSneyders,

here on this PR the Flask version was pinned to `<2`, but we have been using in our company Connexion 2.7.0 with Flask without any problems (maybe we didn't use all the functionality), but here due a pull request related to the CI, we can't upgrade to 2.9.0

Do you know if there is intention to support Flask 2 on the 2.* branch or to revert this change before releasing Connexion 3?

Thanks

**Comment by miguelgf** [comment]
Hello again @RobbeSneyders , I just saw this https://github.com/zalando/connexion/pull/1402 that replies myself.

Thanks anyways :-)

**Pull request merged**
