### PR TITLE
Fix handling additionalProperties in body

### PR DESCRIPTION
**Pull request by krise3k**
Currently when object is send as body parameter only properties defined in `properties` in body schema are passed to handler function. Additional keys are filtered out, which is opposite to [spec](https://github.com/OAI/OpenAPI-Specification/blame/3.0.2/versions/3.0.2.md#L2305). For me specification is counter intuitive :(

Changes proposed in this pull request:
 - If `additionalProperties` is not set or is `True`, all properties not defined in `properties` are passed without type casting.
 - If `additionalProperties` declares value type,  unknown properties are cast according to https://github.com/zalando/connexion#type-casting.

The best explanation for `additionalProperties` I found in https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-218829120

### CODE REVIEW

**Comment by jmcs** [comment]
Can you also update the documentation. Thanks for the PR.

**Comment by dtkav** [comment]
IMHO the important part to document with respect to connexion is that the type-casting magic will only work for properties that are defined in the schema.
Otherwise I don't think this new behavior is surprising, I just implemented it wrong originally (so this is a bugfix).

**Comment by cziebuhr** [comment]
Sanitizing body arguments is fine for individual object properties which are fed as its own argument to handler functions. IMHO the `body` property itself should be passed unchanged without any magic involved (also if `type` != `object` or `type` not specified at all). It better aligns to the current behavior for swagger 2 and to the spec.
Background: I'm currently working on supporting `discriminator` value (polymorphism). Schemas are quite complicated there and we should try to keep the amount of own validation magic (other than what jsonschema does) to a bare minimum.

**Comment by krise3k** [comment]
@jmcs This pull request doesn't introduce new functionality, so I don't know what should be documented. 
It's only fix passing additional properties to handler function on openapi v3.x, which always works for  openapi v2 (swagger)

**Comment by jmcs** [comment]
:+1:

**Comment by krise3k** [comment]
thanks @jmcs

**Pull request merged**
