### PR TITLE
Issue #389 - Add support for x-authentication-scheme and Bearer authentication scheme in apiKey security definition

### PR DESCRIPTION
**Pull request by advance512**
PR for issue #389.

Changes proposed in this pull request:

    Added support for x-authentication-scheme in ApiKeyAuthorization object
    Added x-authentication-scheme field in Authorize dialog
    Automatically adds 'Bearer ' prefix to Authorization header in case x-authentication-scheme is 'Bearer'
    Beautified swagger-ui.js
    Updated swagger-ui.min.js
    index.html now uses minified version of swagger-ui.js for better performance (86.57% compression, saving 2804.37 kb)

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
Hi @advance512! Thank you for working on it. But this PR is impossible to review. Could you please make the necessary changes in the existing files?

**Comment by advance512** [comment]
Good point.

How about you beautify the existing JavaScript in a new commit in the branch master (or develop), and then I'll rebase on that version so you can see the diff?

I used: http://jsbeautifier.org/

It is impossible to do any proper work in the existing JS file.

**Comment by rafaelcaricio** [comment]
That one of the problems of this vendor of the Swagger UI within Connexion. We must find a way to handle this better. We shouldn't be developing on the minified version of the JS. 

We should have a submodule to the original Swagger UI repo under a directory like `/vendor`, plus adding our patch and static files processing (minification, compilation, appending, etc) in the `release.sh` script just before publishing a new Connexion package.

I know it is a lot more work, and I think it is not fair to ask you for that since you want to change something completely different and small. I will try to find time as soon as possible to do some work in this direction and then we can move forward with further modification in those static files. How does it sound?

**Comment by advance512** [comment]
Well, sure. I will try and create another patch, temporarily, that affects just the non-minified field, with the existing JS formatting.

**Comment by rafaelcaricio** [comment]
I have opened an issue for the Swagger UI handling https://github.com/zalando/connexion/issues/406. Lets continue in the new PR #391 to proceed with this change.

**Pull request closed without merging**
