### PR TITLE
Connexion request user

### LINKED ISSUE #433: Regression: module 'connexion.request' has no attribute 'user'
Another regression bug. #432 added support for `flask.request.user`, but we actually "promoted" `connexion.request` at some point (also mentioned in the docs). `connexion.request.user` no longer works:

```
[2017-04-05 17:27:53,592] ERROR in app: Exception on /aws-accounts/123456789012/roles/hjacobs/credentials [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/security.py", line 90, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/validation.py", line 299, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "/app.py", line 49, in get_credentials
    uid = connexion.request.user
AttributeError: module 'connexion.request' has no attribute 'user'
```

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Fixes #433 

Adds back the support to `connexion.request` instance pointing to `flask.request`.

Also simplifies some parts of the codebase with unnecessary complexity.

> "Simple is better than complex."
[The Zen of Python](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python)

### CODE REVIEW

**Comment by hjacobs** [comment]
@rafaelcaricio can you add one test to make sure we won't introduce a similar regression bug in the future again?

**Comment by rafaelcaricio** [comment]
@hjacobs Done.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@rafaelcaricio please release it! :smile:

**Pull request merged**
