### PR TITLE
Update test_bootstrap.py

### PR DESCRIPTION
**Pull request by yota0613**
Fixes # .

Changes proposed in this pull request:

 -
 -
 -

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
What is the objective of this PR?

**Comment by obskyr** [comment]
Probably to get the Hacktoberfest t-shirt. Should probably report this PR as spam.

**Comment by rafaelcaricio** [comment]
@obskyr where do I report this?

**Comment by obskyr** [comment]
@rafaelcaricio Ah, I guess you technically report the user from their profile, not the PR. I'm not entirely sure how GitHub views frivolous pull requests, though, but it shouldn't hurt.

**Pull request closed without merging**
