### PR TITLE
Fix swagger console backslash redirect for aiohttp (thanks @pando85)

### LINKED ISSUE #831: URL for UI must have ui/
### Description

In 2.1, the url for the ui must have a slash after ui (e.g., https://site.name/ui/)  Request to https://site.name/ui fail

### Expected behaviour

https://site.name/ui should work the same as https://site.name/ui/

### Actual behaviour

Throws a 500 error with the following logs:

```ERROR:root:----- Server Exception -----
Error: 301 Moved Permanently: None
Traceback:
Traceback (most recent call last):
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 1538, in match
    rv = rule.match(path, method)
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 776, in match
    raise RequestSlash()
werkzeug.routing.RequestSlash
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/ubuntu/foo/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 1542, in match
    safe='/:|+') + '/', query_args))
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None```


### Steps to reproduce

Using swagger (openapi 2) definition in connexion.

Visit https://site.name/ui

### Additional info:

Output of the commands:

Python 3.6.5 :: Anaconda, Inc.

connexion 2.1.0

### PR DESCRIPTION
**Pull request by dtkav**
Fixes #831 

Changes proposed in this pull request:
 - redirect ui -> ui/ for aiohttp

### CODE REVIEW

**Comment by jmcs** [comment]
Won't this introduce a mismatch between this endpoint and all the others?

**Comment by dtkav** [comment]
@jmcs good point. I guess the best path forward is to look into enabling this for all routes on aiohttp to make the behavior similar to flask?

**Comment by dtkav** [comment]
It turns out we have to manually add a redirect for this route specifically because AioHttp removes the trailing slash from the static_files route (ui/*).

See https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L1049

I'll also add the middleware for redirecting all other routes to trailing slashes.

**Comment by dtkav** [comment]
Note, this depends on #823

**Comment by dtkav** [comment]
Wow this was a real rabbit hole to go down. :rabbit: 
It turns out that some clients will turn POST requests into GET requests on a (301|302|303) redirect!
This is working nicely now with 308 redirect (https://tools.ietf.org/html/rfc7538).

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
