### PR TITLE
Adds Object based resolver

### PR DESCRIPTION
**Pull request by dannypurcell**
A slightly different style of name resolution. Makes the logistics a bit easier with multiple base endpoints meeting the same API spec.

### CODE REVIEW

**Comment by hjacobs** [comment]
Could you explain the purpose/use case and add tests?

**Comment by danielpsf** [comment]
I'd love to use it as soon as it gets merged. Any news when this will become available?

**Comment by jmcs** [comment]
@dannypurcell are you still interested in merging this PR? If so please provide tests and documentation, including what use cases this solve and how this works.

**Comment by hjacobs** [comment]
I'm closing this PR for now (as it's pretty old and there are no recent updates).

**Pull request closed without merging**
