### PR TITLE
Handle array of definition and definition properties in a definition

### PR DESCRIPTION
**Pull request by cyprien-g**
Handle properties with a list of definition:

```YAML
- in: body
  description: Tracks
  name: body
  required: false
  schema:
      type: array
      items:
         $ref: "#/definitions/Track"
```

Handle also definitions which have properties with definition:

```YAML
  Track:
    type: object
    required:
      - title
    properties:
      id:
        type: string
        format: string
      title:
        type: string
        format: string
      release:
        $ref: "#/definitions/FullRelease"
```

### CODE REVIEW

**Comment by cyprien-g** [comment]
@jmcs @hjacobs when do you think you can review it ?

**Comment by hjacobs** [comment]
@cyprien-g sorry, for not having it reviewed yet, will do

**Comment by hjacobs** [comment]
@cyprien-g the latest merge of #117 produced a conflict, please resolve :-)
Thanks!

**Comment by hjacobs** [comment]
@cyprien-g I was "lazy" and did some code clean up of your pull request after merging (instead of telling you / commenting), please compare: https://github.com/zalando/connexion/commit/7320ed280f074bf0327503d47001068b01eeaa3d

**Pull request merged**
