### PR TITLE
Add Ruwan Lambrichts & Robbe Sneyders as maintainers

### PR DESCRIPTION
**Pull request by RobbeSneyders**
Adding Ruwan & myself to MAINTAINERS as discussed in #1365.
Looking forward help maintain Connexion, thanks a lot! :)

Note that this is the first PR that targets the new `main` branch instead of `master`.

### CODE REVIEW

**Review by rafaelcaricio — APPROVED** [review]

**Comment by RobbeSneyders** [comment]
@hjacobs seems like Zappr is also active on PRs towards the main branch.

**Comment by rafaelcaricio** [comment]
👍🏽

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@RobbeSneyders yeah, but the check is not "required", so you can merge without the Zappr approval.

**Pull request merged**
