### PR TITLE
improved error 415

### PR DESCRIPTION
**Pull request by parthsujalshah**
As per the issue #1181 , the 415 response now is improved!

### CODE REVIEW

**Comment by hjacobs** [comment]
Can you add a test for this change?

**Comment by parthsujalshah** [comment]
I have added the test

**Comment by parthsujalshah** [comment]
What do I need to add in swagger.yaml and openapi.yaml files for erro 415?

**Comment by hjacobs** [comment]
The Travis build is currently failing: https://travis-ci.org/github/zalando/connexion/builds/671478075

**Review by Ruwann — APPROVED** [review]

**Comment by Ruwann** [comment]
@hjacobs I fixed the failing tests/build, so I think this one can be merged now. WDYT?

**Pull request merged**
