### PR TITLE
Allow nesting of path resources in RestyResolver

### LINKED ISSUE #206: Handle nested paths in swagger definitions
Connexion does not seem to handle nested paths.
Tried loading the example Uber swagger spec provided at [editor.swagger.io](editor.swagger.io).
Using RestyResolver to perform view resolution with 'api' as module.
Added placeholder views for all path actions.
Python 3.5.1 on MacOS
The spec has the following paths defined:
- /estimates/time
- /estimates/price
  Fails with `Attribute error: module 'api.estimates' has no attribute 'get'`
  There is no `get` action defined at the /estimates path although this seems to be what the resolver is looking for.
  I would expect it to use /api/estimates/time.py with get method and /api/estimates/price.py with get method instead.

### PR DESCRIPTION
**Pull request by drewsonne**
Fixes #206 - Handle nested paths in swagger definitions.

Changes proposed in this pull request:

 - Allow nested paths to be handled in `get` and `search` handlers

An explicit decision has been made to resolve paths (with a prefix like `my.api`) like:
 - `/hello/{hello_id}/world` --> `my.api.hello.world:search(hello_id)`
 - `/hello/world/{world_id}` --> `my.api.hello.world:get(world_id)`

Any solution using concatenated method names (`my.api.hello:world_search(hello_id)`) as discussed in the issue above, should be done in subsequent PR's in the spirit of small incremental changes.

### CODE REVIEW

**Comment by tristanhoskenjs** [comment]
👍

**Comment by jmcs** [comment]
Please add this feature and behaviour to the documentation.

**Comment by drewsonne** [comment]
> Please add this feature and behaviour to the documentation.

Done

**Comment by jmcs** [comment]
:+1:

**Comment by jmcs** [comment]
Thanks for the PR.

**Comment by languitar** [comment]
Any plans for a new release including these changes? We'd like to use them.

**Pull request merged**
