### PR TITLE
add oas3 examples

### PR DESCRIPTION
**Pull request by dtkav**
Relates to #420 
Split out examples from #621 to make code review easier.

Changes proposed in this pull request:
 - move existing examples under examples/swagger2
 - add more examples under examples/openapi

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks!

**Comment by Ryan-Gordon** [comment]
Hey @dtkav , went to check out your PR as I was thinking of updating some of the examples to OAS3 also but found yours, when I try to run the projects I get this error :  
`swagger_spec_validator.common.SwaggerValidationError: 'swagger' is a required property`  
If the connexion library isn't fully ready for OAS3 that may be why but could you confirm if these run on your local machine ?

**Comment by dtkav** [comment]
hey @Ryan-Gordon - this PR was split out from #621 (add oas3 support) in order to make that PR smaller and more reviewable. We are working towards a 2.0 release of Connexion (that will include OpenAPI3 support) on the dev-2.0 branch. The idea is that we'll merge some backwards-incompatible changes, improvements, oas3 support, and then these examples.

**Comment by Ryan-Gordon** [comment]
Hey @dtkav, 
Just checked out that other PR and can see quite a bit of work there so its all making alot more sense now. Thank you for clarifying !

**Comment by dtkav** [comment]
Thanks @JuxhinDB

**Pull request merged**
