### PR TITLE
Add API reference documentation

### LINKED ISSUE #993: Add API reference documentation
### Description

The connexion documentation does currently not contain a section with the API reference, which should document each module, class, and function. API reference documentation is very useful when developing both on and with connexion, and might improve contributions/adoption.

API reference documentation can be generated automatically from the docstrings with Sphinx extensions:
- [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) (imports code)
- [AutoAPI](https://github.com/readthedocs/sphinx-autoapi) (parses source code statically)

This will also be an incentive to improve / add missing docstrings in the connexion code base.

### Expected behaviour

An good example can be found in the Flask documentation. http://flask.pocoo.org/docs/1.0/#api-reference

### PR DESCRIPTION
**Pull request by RobbeSneyders**
Fixes #993 

Some functionality of connexion is not explicitly documented (eg. the available `options` to pass to connexion). Exposing API reference documentation should help users find this functionality, and allows us to link to it in the written documentation. 

Changes proposed in this pull request:
 - Add auto generated API documentation
 - Fix formatting errors in docstrings 
 - Add flake8 rst docstring check

@jmcs guessing that you set up the connexion readthedocs. The version currently on there is quite old (seems to be the `dev-2.0` branch). Could you change the default branch to `main` and [activate documentation building for this PR](dev-2.0l)?

### CODE REVIEW

**Comment by hjacobs** [comment]
@RobbeSneyders I updated ReadTheDocs, it now uses the `main` branch: https://connexion.readthedocs.io/

**Comment by RobbeSneyders** [comment]
Thanks @hjacobs. The API reference documentation is not showing up though. Any information from the ReadTheDocs console on what's going wrong?

**Comment by hjacobs** [comment]
Screenshot 2021-07-07 at 09-00-21 connexion Read the Docs

@RobbeSneyders I can add you as maintainer to ReadTheDocs if you tell me your ReadTheDocs username.

**Comment by hjacobs** [comment]
@RobbeSneyders ticking "install project" fixes the `connexion` module, but now `autoapi` needs to be there as dependency:
Screenshot 2021-07-07 at 09-02-52 connexion Read the Docs

**Comment by RobbeSneyders** [comment]
I just registered on ReadTheDocs with username RobbeSneyders.

Since the dependency is only for the docs, I added docs specific requirements in #1391.

**Pull request merged**
